airline/airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("flights/", include ("flights.urls", namespace="flights")),
    path("users/", include ("users.urls", namespace="users")),
    path("users/", include ("django.contrib.auth.urls"))
]

airline/flights/urls.py
from django.urls import path

from . import views

app_name = "flights"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book") 
]

airline/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login_view, name="login"),
    path("login/logout/", views.logout_view, name="logout"),   
]

airline/flights/models.py
from django.db import models

# Create your models here.  

class Airport(models.Model):
    code = models.CharField(max_length=32)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete= models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete= models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        
        return f"{self.id}: {self.origin} to {self.destination}"

class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank= True, related_name="passengers")

    def __str__(self):
        return f"{self.first} {self.last}"       

airline/users/models.py
from django.db import models

# Create your models here.

airline/flights/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Flight, Passenger

# Create your views here.

def index(request):
    return render (request, "flights/index.html", {
        "flights": Flight.objects.all()
    })

def flight(request, flight_id):
    flight = Flight.objects.get(id=flight_id)
    return render (request, "flights/flight.html", {
        "flight": flight,
        "passengers": flight.passengers.all(),
        "non_passengers":Passenger.objects.exclude(flights=flight).all()
    })    

def book(request, flight_id):
    if request.method == "POST":
        flight = Flight.objects.get(id=flight_id)
        passenger = Passenger.objects.get(id=request.POST["passenger"])
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse("flights:flight", args=(flight.id,)))

airline/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User

# Create your views here.

def index(request):

    return render(request, "users/index.html")

def signup(request):

    if request.method == "POST":

        username = request.POST["username"]
        first = request.POST["first"]
        last = request.POST["last"]
        email = request.POST["email"]
        password = request.POST["password"]

        newuser = User.objects.create_user(username,email,password)
        newuser.first_name = first
        newuser.last_name = last

        newuser.save()

        return redirect("login")
    else:

        return render(request, "users/signup.html")    

def login_view(request):
    if request.method == "POST":

        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(username = username, password = password)

        if user is not None :
            login(request, user)

            first = user.first_name

            return render(request, "users/home.html", {
                "first": first
                })
        else:
            
            return render(request, "users/signin.html", {
                "message": "Invalid Credentials"
            })
    
    else:

        return render(request, "users/signin.html")

def logout_view(request):
    logout(request)
    return redirect("index")

airline/flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
<h1>Flight : {{ flight.id }}</h1>
<ul>
    <li>Origin: {{ flight.origin}}</li>
    <li>Destination: {{flight.destination}}</li>
    <li>Duration: {{flight.duration}}</li>
</ul>

<h2>Passengers</h2>
<ul>
    {% for passenger in passengers %}
    <li>{{passenger}}</li>
    {% empty %}
    <li>No Passengers</li>
    {% endfor %}
</ul>

<h2> Add Passengers</h2>
     
<form action="{% url 'flights:book' flight.id %}" method="post">
     {% csrf_token %}
     <select name="passenger">
        {% for passenger in non_passengers %}
              <option value="{{ passenger.id }}">{{ passenger }}</option>
        {% endfor %}     
     </select>
     <input type="submit">
</form> 


 
{% endblock %}

airline/flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
<h1>Flights</h1>
<ul>
    {% for flight in flights %}
    <li>
        <a href="{% url 'flights:flight' flight.id %}">
        Flight {{flight.id}}: {{flight.origin}} to {{flight.destination}}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

airline/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>FLIGHTS</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

airline/users/templates/users/home.html
{% extends "users/layout.html" %}

{% block body%}

  <h2>Hello {{ first }}</h2>

   <button type="submit"><a href="logout">Sign Out</a></button>


{% endblock %}>

airline/users/templates/users/index.html
{% extends "users/layout.html" %}

{% block body%}

  <h1>Welcome</h1>

   <button type="submit"><a href="signup">Sign up</a></button>
   <button type="submit"><a href="login">Sign in</a></button>

{% endblock %}

airline/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>USERS</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

airline/users/templates/users/signin.html
{% extends "users/layout.html" %}

{% block body%}

       {% if message %}
           <div>{{ message }}</div>
       {% endif %}    

   <h2>Sign In</h2>
   <form action="{% url 'login' %}" method="post">

       {% csrf_token %}
            <label for="">Username</label>
            <input type="text" name="username" placeholder="Username">

            <label for="">Password</label>
            <input type="password" name="password" placeholder="Password">

            <button type="submit">Sign In</button>
   </form>
   <br>

   <a href = "{% url 'users:signup' %}">Create Account</a>
{% endblock %}

airline/users/templates/users/signup.html
{% extends "users/layout.html" %}

{% block body%}
    <h2>Sign Up</h2>
   <form action="{% url 'users:signup' %}" method="post">

       {% csrf_token %}
            <label for="">Username</label>
            <input type="text" name="username" placeholder="Username">

            <label for="">First Name</label>
            <input type="text" name="first" placeholder="first">
            
            <label for="">Last Name</label>
            <input type="text" name="last" placeholder="last">

            <label for="">Email</label>
            <input type="email" name="email" placeholder="Email">

            <label for="">Password</label>
            <input type="password" name="password" placeholder="Password">

            <button type="submit">Sign Up</button>
   </form>
{% endblock %}